sudo: required
dist: xenial
language: python


python:
  - 3.8
  - 3.9


env:
  - TOXENV=py


matrix:
  fast_finish: true

before_cache:
  - |
      rm -f $HOME/.cache/pip/log/debug.log

cache:
    directories:
        - $HOME/.cache/pip

install:
    - pip install -U pip pipenv tox tox-pipenv
    - pip install -U numpy

script:
    - set -o pipefail
    - tox
